print("----ejemplo---")
print("Suma:", 5+3)
print("Resta:", 10-4)
print("Multiplicacion:", 3*4)
print("Division:", f"{10/3}")
print("Division entera:", f"{10/3}")
print("Division entera:", 10//3)
print("Modulo:", 10%3)
print("Potencia:", 2**3)

print("----propio------")
print("Suma:", 10+34)
print("Resta:", 234-43)
print("Multiplicacion:", 1*5)
print("Division:", f"{6540/10}")
print("Division entera:", f"{500/20}")
print("Division entera:", 250//2)
print("Modulo:", 20%2)
print("Potencia:", 4**6)
